################################################################
# FILE NAME: makefile                                          #
#                                                              #
# DESCRIPTION:                                                 #
#   makefile for "pi calculator" sample program                #
#                                                              #
# COPYRIGHT:                                                   #
#   Licensed Materials - Property of Solution Frameworks       #
#   Copyright (C) 1996, Solution Frameworks                    #
#   All Rights Reserved                                        #
################################################################
CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
INC    = /I..\pi /I..\userevt
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
!else
ODIR=.\win
!endif


ALL :  CREATEDIR PI USEREVT $(ODIR)\picalc.exe

$(ODIR)\picalc.exe : $(ODIR)\picalc.obj \
                     ..\pi\$(ODIR)\pi.obj \
                     ..\userevt\$(ODIR)\userevt.obj
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$@ $**

$(ODIR)\picalc.obj : picalc.cpp \
                       ..\pi\pi.hpp \
                       ..\userevt\userevt.hpp
   icc $(CFLAGS) $(INC) /C+ /Fo$@ picalc.cpp

PI :
  cd ..\pi
  nmake
  cd ..\picalc

USEREVT :
  cd ..\userevt
  nmake
  cd ..\picalc

CREATEDIR:
  @if not exist $(ODIR) md $(ODIR)

