/************************************************************
/ Container Control - Dates and Times as IDate/ITime        
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ Copyright (c) 1997 John Wiley & Sons, Inc. 
/ All Rights Reserved.
************************************************************/
#define ID_DEVELOPER      1000


#define DEVELOPER_WINDOW     1500
#define DEVELOPER_CONTAINER  1501
