//*********************************************************
// Getting Started - Simple Program, Version 2
//
// Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
// Copyright (c) 1997 John Wiley & Sons, Inc. 
// All Rights Reserved.
//*********************************************************

// Window identifiers.
#define ID_CODEWINDOW 1000

// Command identifiers.
#define CMD_CUT       2001
#define CMD_COPY      2002
#define CMD_PASTE     2003

// Other menu-bar related identifiers.
#define ID_FILE       1001
#define ID_EDIT       1002
