## Advanced Frame - Dialog Window Example

CFLAGS = /Ft- /Gd+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
LIBS =
ODIR=.\os2
RC=rc.exe -DIC_PM
RCOUT=
!else
LIBS =
ODIR=.\win
RC=irc.exe
RCOUT=-Fo
!endif
ORES=$(ODIR)\tstdlg.res

OBJS = $(ODIR)\tstdlg.obj $(ODIR)\dialog.obj $(ODIR)\dlghndlr.obj

ALL : CREATEDIR $(ODIR)\tstdlg.exe

$(ODIR)\tstdlg.exe : $(OBJS) $(ORES)
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" $(LIBS) /Fe$@ $(OBJS)
   $(RC) $(ORES) $@
!else
   icc $(CFLAGS) /B"$(LFLAGS)" $(LIBS) /Fe$@ $**
!endif

tstdlg.cpp   :
dialog.cpp   : dialog.hpp dlghndlr.hpp
dlghndlr.cpp : dlghndlr.hpp

{.}.cpp{$(ODIR)}.obj:
   icc $(CFLAGS) /C+ /Fo$@ $(@B).cpp

$(ORES): tstdlg.rc
   $(RC) -r $(@B).rc $(RCOUT)$@

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
