## Container Control - Delayed Page Loading

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\minicnr.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\minicnr.res
!endif


ALL : CREATEDIR   $(ODIR)\minicnr.exe

$(ODIR)\minicnr.exe :  $(ODIR)\minicnr.obj $(ODIR)\minicnr.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\minicnr.exe $(ODIR)\minicnr.obj
   $(RC) $(ODIR)\minicnr.res  $(ODIR)\minicnr.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\minicnr.exe  $(ODIR)\minicnr.obj $(ODIR)\minicnr.res
!endif

$(ODIR)\minicnr.obj: minicnr.cpp minicnr.h
   icc $(CFLAGS) /C+  /Fo$(ODIR)\minicnr.obj  minicnr.cpp

$(ODIR)\minicnr.res:  minicnr.rc minicnr.h
   $(RC) -r minicnr.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
