## Menus - Using a Menu Cursor

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\cursor.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\cursor.res
!endif


ALL :  CREATEDIR  $(ODIR)\cursor.exe

$(ODIR)\cursor.exe :  $(ODIR)\cursor.obj $(ODIR)\cursor.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\cursor.exe $(ODIR)\cursor.obj
   $(RC) $(ODIR)\cursor.res $(ODIR)\cursor.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\cursor.exe $(ODIR)\cursor.obj $(ODIR)\cursor.res
!endif

$(ODIR)\cursor.obj : cursor.cpp cursor.h
   icc $(CFLAGS) /C+ /Fo$(ODIR)\cursor.obj cursor.cpp

$(ODIR)\cursor.res : cursor.rc cursor.h
   $(RC) -r cursor.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
