## Canvas - Lunch Dialog Using IMultiCellCanvas

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\mclunch.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\mclunch.res
!endif


ALL : CREATEDIR $(ODIR)\mclunch.exe

$(ODIR)\mclunch.exe : $(ODIR)\mclunch.obj $(ODIR)\mclunch.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\mclunch.exe $(ODIR)\mclunch.obj
   $(RC) $(ODIR)\mclunch.res $(ODIR)\mclunch.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\mclunch.exe $(ODIR)\mclunch.obj \
       $(ODIR)\mclunch.res
!endif

$(ODIR)\mclunch.obj: mclunch.cpp pushbtns.hpp mclunch.h
   icc $(CFLAGS) /C+ /Fo$(ODIR)\mclunch.obj mclunch.cpp

$(ODIR)\mclunch.res: mclunch.rc mclunch.h
   $(RC) -r mclunch.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
