/**********************************************************
/ Using Help - Help Menu Choices
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ Copyright (c) 1997 John Wiley & Sons, Inc.
/ All Rights Reserved.
**********************************************************/
// Help panel identifiers.
#define PANEL_PRIMARY                   1000
#define PANEL_SECONDARY_BUTTON          1001
#define PANEL_EXIT_BUTTON_PRIMARY       1002
#define PANEL_FILE                      1010
#define PANEL_CLOSE                     1011
#define PANEL_HELP                      1012
#define PANEL_HELPCONTENTS              1013
#define PANEL_HELPINDEX                 1014
#define PANEL_EXTENDEDHELP              1015
#define PANEL_USINGHELP                 1016
#define PANEL_KEYSHELP                  1017
#define PANEL_PRODUCT_INFO              1018
#define PANEL_SECONDARY                 3000
#define PANEL_EXIT_BUTTON_SECONDARY     3001
#define PANEL_KEYS_HELP                 4000
#define PANEL_PRODUCT_INFO_MSG          5000
#define PANEL_CONTENTS                 10000
#define PANEL_INDEX                    10001
