## Using Help - Help Menu Choices

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\helpmenu.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -DIC_WIN -Fo$(ODIR)\helpmenu.res
!endif


ALL : CREATEDIR $(ODIR)\helpmenu.exe $(ODIR)\helpmenu.hlp

$(ODIR)\helpmenu.exe : $(ODIR)\helpmenu.obj $(ODIR)\helpmenu.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\helpmenu.exe $(ODIR)\helpmenu.obj
   $(RC) $(ODIR)\helpmenu.res $(ODIR)\helpmenu.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\helpmenu.exe $(ODIR)\helpmenu.obj \
       $(ODIR)\helpmenu.res
!endif

$(ODIR)\helpmenu.obj: helpmenu.cpp helpmenu.hpp hkeyshdr.hpp hcmdhdr.hpp \
                      helpmenu.h hlppanel.h
!ifdef IPF_COMPATIBLE
   icc $(CFLAGS) /C+ /DIPF_COMPATIBLE /Fo$(ODIR)\helpmenu.obj helpmenu.cpp
!else
   icc $(CFLAGS) /C+ /Fo$(ODIR)\helpmenu.obj helpmenu.cpp
!endif

$(ODIR)\helpmenu.res: helpmenu.rc helpmenu.h hlppanel.h
!ifdef IPF_COMPATIBLE
   $(RC) -r -dIPF_COMPATIBLE helpmenu.rc $(ORES)
!else
   $(RC) -r helpmenu.rc $(ORES)
!endif

!ifdef IC_PM
$(ODIR)\helpmenu.hlp: helpmenu.ipf hlppanel.h
   icc /Pc- /Pe+ /Tdp helpmenu.ipf
   ipfc helpmenu.i /x
   del  helpmenu.i
!else
!ifdef IPF_COMPATIBLE
$(ODIR)\helpmenu.hlp: helpmenu.ipf hlppanel.h
   icc /Pc- /Pe+ /Tdp helpmenu.ipf
   ipfc helpmenu.i /x /q
   del  helpmenu.i
!else
$(ODIR)\helpmenu.hlp: helpmenu.hpj helpmenu.rtf hlppanel.h
   hcw /c /e helpmenu.hpj
!endif
!endif
   copy helpmenu.hlp $(ODIR)
   del  helpmenu.hlp

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)

