## Reusable Handlers - Simple Command Handler

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\cmdhdrs.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\cmdhdrs.res
!endif


ALL :  CREATEDIR  $(ODIR)\cmdhdrs.exe

$(ODIR)\cmdhdrs.exe : $(ODIR)\cmdhdrs.obj $(ODIR)\cmdhdrs.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\cmdhdrs.exe $(ODIR)\cmdhdrs.obj
   $(RC) $(ODIR)\cmdhdrs.res $(ODIR)\cmdhdrs.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\cmdhdrs.exe $(ODIR)\cmdhdrs.obj $(ODIR)\cmdhdrs.res
!endif

$(ODIR)\cmdhdrs.obj: cmdhdrs.cpp cmdhdr1.hpp cmdhdr2.hpp popuphdr.hpp
   icc $(CFLAGS) /C+ /Fo$(ODIR)\cmdhdrs.obj cmdhdrs.cpp

$(ODIR)\cmdhdrs.res: cmdhdrs.rc cmdhdrs.h
   $(RC) -r cmdhdrs.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
