## Container Control - Combined Tree and Details View

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\treedet.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\treedet.res
!endif

OBJS=$(ODIR)\treedet.obj $(ODIR)\treedetc.obj $(ODIR)\treedeth.obj $(ODIR)\partlist.obj $(ODIR)\partobj.obj

ALL : CREATEDIR   $(ODIR)\treedet.exe

$(ODIR)\treedet.exe : $(OBJS)  $(ODIR)\partlist.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\treedet.exe $(OBJS)
   $(RC) $(ODIR)\treedet.res  $(ODIR)\treedet.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\treedet.exe  $(OBJS) $(ODIR)\treedet.res
!endif

$(ODIR)\treedet.obj: treedet.cpp partlist.hpp
   icc $(CFLAGS) /C+  /Fo$(ODIR)\treedet.obj  treedet.cpp

$(ODIR)\treedetc.obj: treedetc.cpp treedetc.hpp
   icc $(CFLAGS) /C+  /Fo$(ODIR)\treedetc.obj  treedetc.cpp

$(ODIR)\treedeth.obj: treedeth.cpp treedeth.hpp treedetc.hpp
   icc $(CFLAGS) /C+  /Fo$(ODIR)\treedeth.obj  treedeth.cpp

$(ODIR)\partlist.obj: partlist.cpp partlist.hpp partlist.h partobj.hpp treedetc.hpp treedeth.hpp
   icc $(CFLAGS) /C+  /Fo$(ODIR)\partlist.obj  partlist.cpp

$(ODIR)\partobj.obj: partobj.cpp partobj.hpp
   icc $(CFLAGS) /C+  /Fo$(ODIR)\partobj.obj  partobj.cpp

$(ODIR)\partlist.res:  partlist.rc partlist.h
   $(RC) -r partlist.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
