## Container Control - Dates and Times as CDATE/CTIME

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\cdate.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\cdate.res
!endif


ALL : CREATEDIR   $(ODIR)\cdate.exe

$(ODIR)\cdate.exe :  $(ODIR)\cdate.obj $(ODIR)\cdate.res $(ODIR)\developr.obj
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\cdate.exe $(ODIR)\cdate.obj $(ODIR)\developr.obj
   $(RC) $(ODIR)\cdate.res  $(ODIR)\cdate.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\cdate.exe  $(ODIR)\cdate.obj $(ODIR)\developr.obj $(ODIR)\cdate.res
!endif

$(ODIR)\cdate.obj: cdate.cpp developr.h developr.hpp
   icc $(CFLAGS) /C+  /Fo$(ODIR)\cdate.obj  cdate.cpp

$(ODIR)\developr.obj: developr.cpp developr.h developr.hpp
   icc $(CFLAGS) /C+  /Fo$(ODIR)\developr.obj  developr.cpp

$(ODIR)\cdate.res:  cdate.rc developr.h
   $(RC) -r cdate.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
