## Extending the Library - Value Set Example   

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\testvset.res
RC=rc.exe -DIC_PM

OBJS = $(ODIR)\testvset.obj $(ODIR)\valueset.obj $(ODIR)\vsethdr.obj $(ODIR)\vsetevt.obj

ALL : CREATEDIR $(ODIR)\testvset.exe

$(ODIR)\testvset.exe : $(OBJS) $(ODIR)\testvset.res
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\testvset.exe $(OBJS)
   $(RC) $(ODIR)\testvset.res $(ODIR)\testvset.exe

$(ODIR)\testvset.obj: testvset.cpp testvset.h valueset.hpp vsethdr.hpp
   icc $(CFLAGS) /C+ /Fo$(ODIR)\testvset.obj testvset.cpp

$(ODIR)\valueset.obj: valueset.cpp valueset.hpp 
   icc $(CFLAGS) /C+ /Fo$(ODIR)\valueset.obj valueset.cpp

$(ODIR)\vsethdr.obj: vsethdr.cpp  valueset.hpp vsethdr.hpp
   icc $(CFLAGS) /C+ /Fo$(ODIR)\vsethdr.obj vsethdr.cpp

$(ODIR)\vsetevt.obj: vsetevt.cpp  vsetevt.hpp
   icc $(CFLAGS) /C+ /Fo$(ODIR)\vsetevt.obj vsetevt.cpp

$(ODIR)\testvset.res: testvset.rc testvset.h
   $(RC) -r testvset.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)

!else
ALL :  DISPLAYMSG

DISPLAYMSG:
  @echo This sample is not supported on the Windows operating systems.
!endif
