/************************************************************
/ Advanced Frame - Window Viewer Example
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ Copyright (c) 1997 John Wiley & Sons, Inc. 
/ All Rights Reserved.
************************************************************/

#define WND_MAIN    100
#define POPUP_MENU  200

#define MI_FILE     100
#define MI_EXIT     101
#define MI_SELECTED 200
#define MI_OPENICON 201
#define MI_OPENINFO 202
#define MI_REFRESH  300

#define APP_ICON_ID 101
