## Using Help - Help Tables

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\helptbl.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -DIC_WIN -Fo$(ODIR)\helptbl.res
!endif


ALL : CREATEDIR $(ODIR)\helptbl.exe $(ODIR)\helptbl.hlp

$(ODIR)\helptbl.exe : $(ODIR)\helptbl.obj $(ODIR)\helptbl.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\helptbl.exe $(ODIR)\helptbl.obj
   $(RC) $(ODIR)\helptbl.res $(ODIR)\helptbl.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\helptbl.exe $(ODIR)\helptbl.obj \
       $(ODIR)\helptbl.res
!endif

$(ODIR)\helptbl.obj: helptbl.cpp helptbl.h hlppanel.h
!ifdef IPF_COMPATIBLE
   icc $(CFLAGS) /C+ /DIPF_COMPATIBLE /Fo$(ODIR)\helptbl.obj helptbl.cpp
!else
   icc $(CFLAGS) /C+ /Fo$(ODIR)\helptbl.obj helptbl.cpp
!endif

$(ODIR)\helptbl.res: helptbl.rc helptbl.h hlppanel.h
   $(RC) -r helptbl.rc $(ORES)

!ifdef IC_PM
$(ODIR)\helptbl.hlp: helptbl.ipf hlppanel.h
   icc /Pc- /Pe+ /Tdp helptbl.ipf
   ipfc helptbl.i /x
   del  helptbl.i
!else
!ifdef IPF_COMPATIBLE
$(ODIR)\helptbl.hlp: helptbl.ipf hlppanel.h
   icc /Pc- /Pe+ /Tdp helptbl.ipf
   ipfc helptbl.i /x /q
   del  helptbl.i
!else
$(ODIR)\helptbl.hlp: helptbl.hpj helptbl.rtf hlppanel.h
   hcw /c /e helptbl.hpj
!endif
!endif
   copy helptbl.hlp $(ODIR)
   del  helptbl.hlp

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)

