################################################################
# FILE NAME: makefile                                          #
#                                                              #
# DESCRIPTION:                                                 #
#   makefile for "pi" (pi calculation routine) used by a       #
#   number of IThread sample programs.                         #
#                                                              #
# COPYRIGHT:                                                   #
#   Licensed Materials - Property of Solution Frameworks       #
#   Copyright (C) 1996, Solution Frameworks                    #
#   All Rights Reserved                                        #
################################################################
CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:VIO

!ifdef IC_PM
ODIR=.\os2
!else
ODIR=.\win
!endif


ALL :  CREATEDIR  $(ODIR)\pi.obj

$(ODIR)\pi.obj: pi.cpp pi.hpp
   icc $(CFLAGS) /C+ /Fo$(ODIR)\pi.obj pi.cpp

CREATEDIR:
  @if not exist $(ODIR) md $(ODIR)

