#ifndef _PI_
#define _PI_
/**************************************************************
* FILE NAME: pi.hpp                                           *
*                                                             *
* DESCRIPTION:                                                *
*   This file contains the declaration of the function:       *
*     pi - Calculate pi to arbitrary number of digits.        *
*                                                             *
* COPYRIGHT:                                                  *
*   Licensed Materials - Property of Solution Frameworks      *
*   Copyright (C) 1996, Solution Frameworks                   *
*   All Rights Reserved                                       *
**************************************************************/
class IString;

IString pi( unsigned digits );

#endif // _PI_
