/************************************************************
/ Static Controls - Icon and Bitmap Example
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ Copyright (c) 1997 John Wiley & Sons, Inc. 
/ All Rights Reserved.
************************************************************/
//=================== Resource Identifiers ====================
#define ID_CPPICON        1
#define ID_CPPBITMAP      1
