## Static Controls - Icon and Bitmap Example

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\iconbmp.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\iconbmp.res
!endif


ALL : CREATEDIR   $(ODIR)\iconbmp.exe

$(ODIR)\iconbmp.exe :  $(ODIR)\iconbmp.obj $(ODIR)\iconbmp.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\iconbmp.exe $(ODIR)\iconbmp.obj
   $(RC) $(ODIR)\iconbmp.res  $(ODIR)\iconbmp.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\iconbmp.exe  $(ODIR)\iconbmp.obj $(ODIR)\iconbmp.res
!endif

$(ODIR)\iconbmp.obj: iconbmp.cpp iconbmp.h
   icc $(CFLAGS) /C+  /Fo$(ODIR)\iconbmp.obj  iconbmp.cpp

$(ODIR)\iconbmp.res:  iconbmp.rc iconbmp.h
   $(RC) -r iconbmp.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
