//*********************************************************
// Canvas - Complex Canvas Example
//
// Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
// Copyright (c) 1997 John Wiley & Sons, Inc. 
// All Rights Reserved.
//*********************************************************
#include <iapp.hpp>

#include "xcanvas.hpp"
#include "xcanvas.h"

void main ( )
{
  ComplexCanvasWindow
    window;
  IApplication::current().run();
}

