## Canvas - Complex Canvas Example

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\xcanvas.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\xcanvas.res
!endif


ALL : CREATEDIR $(ODIR)\complex.exe

complex.exe : complex.obj xcanvas.obj xcanvas.res
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe.\$*.exe $(LIBS) complex.obj xcanvas.obj
   rc xcanvas.res .\$*.exe
$(ODIR)\complex.exe : $(ODIR)\complex.obj $(ODIR)\xcanvas.obj $(ODIR)\xcanvas.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\complex.exe $(ODIR)\complex.obj \
       $(ODIR)\xcanvas.obj
   $(RC) $(ODIR)\xcanvas.res $(ODIR)\complex.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\complex.exe $(ODIR)\complex.obj \
       $(ODIR)\xcanvas.obj $(ODIR)\xcanvas.res
!endif

$(ODIR)\complex.obj: complex.cpp xcanvas.hpp xcanvas.h pushbtns.hpp
   icc $(CFLAGS) /C+ /Fo$(ODIR)\complex.obj complex.cpp

$(ODIR)\xcanvas.obj: xcanvas.cpp xcanvas.hpp xcanvas.h
   icc $(CFLAGS) /C+ /Fo$(ODIR)\xcanvas.obj xcanvas.cpp

$(ODIR)\xcanvas.res: xcanvas.rc xcanvas.h $(ODIR)\screen.ico
   $(RC) -r xcanvas.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
