/**********************************************************
/ Canvas - Complex Canvas Example
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ Copyright (c) 1997 John Wiley & Sons, Inc. 
/ All Rights Reserved.
**********************************************************/
// Identifiers
#define ID_FOUNTAIN_BMP           101
#define ID_KIDS_BMP               102
#define ID_OLDBOOK_BMP            103
#define ID_SCREEN_ICON            201
