## Canvas - ISetCanvas Pack Options

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\packcv.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\packcv.res
!endif


ALL : CREATEDIR $(ODIR)\setpack.exe

$(ODIR)\setpack.exe : $(ODIR)\setpack.obj $(ODIR)\packcv.obj $(ODIR)\packcv.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\setpack.exe $(ODIR)\setpack.obj \
       $(ODIR)\packcv.obj
   $(RC) $(ODIR)\packcv.res $(ODIR)\setpack.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\setpack.exe $(ODIR)\setpack.obj \
       $(ODIR)\packcv.obj $(ODIR)\packcv.res
!endif

$(ODIR)\setpack.obj: setpack.cpp packcv.hpp packcv.h
   icc $(CFLAGS) /C+ /Fo$(ODIR)\setpack.obj setpack.cpp

$(ODIR)\packcv.obj: packcv.cpp packcv.hpp packcv.h
   icc $(CFLAGS) /C+ /Fo$(ODIR)\packcv.obj packcv.cpp

$(ODIR)\packcv.res: packcv.rc packcv.h $(ODIR)\tl.bmp $(ODIR)\tc.bmp \
       $(ODIR)\tr.bmp $(ODIR)\cl.bmp $(ODIR)\cc.bmp $(ODIR)\cr.bmp \
       $(ODIR)\bl.bmp $(ODIR)\bc.bmp $(ODIR)\br.bmp
   $(RC) -r packcv.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
