## Tool Bars - Animated Button Example

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\animated.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\animated.res
!endif


ALL : CREATEDIR $(ODIR)\animated.exe

$(ODIR)\animated.exe :  $(ODIR)\animated.obj $(ODIR)\animated.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\animated.exe $(ODIR)\animated.obj
   $(RC) $(ODIR)\animated.res  $(ODIR)\animated.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\animated.exe  $(ODIR)\animated.obj $(ODIR)\animated.res
!endif

$(ODIR)\animated.obj: animated.cpp animated.h
   icc $(CFLAGS) /C+  /Fo$(ODIR)\animated.obj  animated.cpp

$(ODIR)\animated.res:  animated.rc animated.h circle1.bmp circle2.bmp circle3.bmp circle4.bmp
   $(RC) -r animated.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
