## Container Control - Tree Icon ViewDelayed Page Loading

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\treeicov.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\treeicov.res
!endif


ALL : CREATEDIR   $(ODIR)\treeicov.exe

$(ODIR)\treeicov.exe :  $(ODIR)\treeicov.obj $(ODIR)\treeicov.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\treeicov.exe $(ODIR)\treeicov.obj
   $(RC) $(ODIR)\treeicov.res  $(ODIR)\treeicov.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\treeicov.exe  $(ODIR)\treeicov.obj $(ODIR)\treeicov.res
!endif

$(ODIR)\treeicov.obj: treeicov.cpp treeicov.h
   icc $(CFLAGS) /C+  /Fo$(ODIR)\treeicov.obj  treeicov.cpp

$(ODIR)\treeicov.res:  treeicov.rc treeicov.h
   $(RC) -r treeicov.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
