## Container Control - Tree Name View

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\treenamv.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\treenamv.res
!endif


ALL : CREATEDIR   $(ODIR)\treenamv.exe

$(ODIR)\treenamv.exe :  $(ODIR)\treenamv.obj $(ODIR)\treenamv.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\treenamv.exe $(ODIR)\treenamv.obj
   $(RC) $(ODIR)\treenamv.res  $(ODIR)\treenamv.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\treenamv.exe  $(ODIR)\treenamv.obj $(ODIR)\treenamv.res
!endif

$(ODIR)\treenamv.obj: treenamv.cpp treenamv.h
   icc $(CFLAGS) /C+  /Fo$(ODIR)\treenamv.obj  treenamv.cpp

$(ODIR)\treenamv.res:  treenamv.rc treenamv.h
   $(RC) -r treenamv.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
