/************************************************************
/ Error Reporting - Exception Viewer Example
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ Copyright (c) 1997 John Wiley & Sons, Inc. 
/ All Rights Reserved.
************************************************************/
#define WND_MAIN         5000           //Main Window Id
#define THROW_EXCEPTION  5001           //Command Id

