## Error Handling - Exception Viewer Example

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\exviewer.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\exviewer.res
!endif


ALL : CREATEDIR  $(ODIR)\exviewer.exe

$(ODIR)\exviewer.exe :  $(ODIR)\exviewer.obj $(ODIR)\exviewer.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\exviewer.exe $(ODIR)\exviewer.obj
   $(RC) $(ODIR)\exviewer.res  $(ODIR)\exviewer.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\exviewer.exe  $(ODIR)\exviewer.obj $(ODIR)\exviewer.res
!endif

$(ODIR)\exviewer.obj: exviewer.cpp exviewer.h
   icc $(CFLAGS) /C+  /Fo$(ODIR)\exviewer.obj  exviewer.cpp

$(ODIR)\exviewer.res:  exviewer.rc exviewer.h
   $(RC) -r exviewer.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)

