## Using Resources - Resources in the EXE


CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS =

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\myeng.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\myeng.res
!endif

ALL :  CREATEDIR  $(ODIR)\exetext.exe

$(ODIR)\exetext.exe : $(ODIR)\exetext.obj $(ODIR)\myeng.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\exetext.exe $(ODIR)\exetext.obj
   $(RC) $(ODIR)\myeng.res $(ODIR)\exetext.exe
!else
   icc $(DFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\exetext.exe $(ODIR)\exetext.obj $(ODIR)\myeng.res
!endif

$(ODIR)\exetext.obj : exetext.cpp mytext.h
   icc $(CFLAGS) /C+ /Fo$(ODIR)\exetext.obj exetext.cpp

$(ODIR)\myeng.res   : myeng.rc mytext.h
   $(RC) -r myeng.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)

