## Frame Window Basics - Information Area for the System Menu

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\infoarea.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\infoarea.res
!endif


ALL :  CREATEDIR  $(ODIR)\infoarea.exe

$(ODIR)\infoarea.exe : $(ODIR)\infoarea.obj $(ODIR)\infoarea.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\infoarea.exe $(ODIR)\infoarea.obj
   $(RC) $(ODIR)\infoarea.res $(ODIR)\infoarea.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\infoarea.exe $(ODIR)\infoarea.obj $(ODIR)\infoarea.res
!endif

$(ODIR)\infoarea.obj: infoarea.cpp
   icc $(CFLAGS) /C+ /Fo$(ODIR)\infoarea.obj infoarea.cpp

$(ODIR)\infoarea.res: infoarea.rc
   $(RC) -r infoarea.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
