## Data Types - Creating Dates and Times from IStrings 

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft- 
LFLAGS = 

!ifdef IC_PM
ODIR=.\os2
!else
ODIR=.\win
!endif


ALL : CREATEDIR   $(ODIR)\stparse.exe

$(ODIR)\stparse.exe :  $(ODIR)\stparse.obj
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\stparse.exe $(ODIR)\stparse.obj

$(ODIR)\stparse.obj: stparse.cpp
   icc $(CFLAGS) /C+  /Fo$(ODIR)\stparse.obj  stparse.cpp

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
