## Advanced Frame Window - Drawing Extensions

CFLAGS = /Ft- /Gd+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
LIBS =
ODIR=.\os2
!else
LIBS =
ODIR=.\win
!endif

ALL :  CREATEDIR $(ODIR)\drawextn.exe


$(ODIR)\drawextn.exe : $(ODIR)\drawextn.obj $(ODIR)\myframe.obj $(ODIR)\myextns.obj
   icc $(CFLAGS) /B"$(LFLAGS)" $(LIBS) /Fe$@ $**

drawextn.cpp  : myframe.hpp
myframe.cpp   : myframe.hpp myextns.hpp
myextns.cpp   : myextns.hpp

{.}.cpp{$(ODIR)}.obj:
   icc $(CFLAGS) /C+ /Fo$@ $(@B).cpp

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
