/**********************************************************
/ Using Help - Help for Special Cases
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ Copyright (c) 1997 John Wiley & Sons, Inc.
/ All Rights Reserved.
**********************************************************/
// Help panel identifiers.
#define PANEL_PRIMARY                1000
#define PANEL_CONTAINER              1001
#define PANEL_PAGE1                  2100
#define PANEL_PAGE1_TAB              2101
#define PANEL_ENTRY1                 2102
#define PANEL_ENTRY3                 2103
#define PANEL_PAGE2                  2200
#define PANEL_PAGE2_TAB              2201
#define PANEL_ENTRYA                 2202
#define PANEL_ENTRYC                 2203
#define PANEL_PAGE3                  2300
#define PANEL_PAGE3_TAB              2301
#define PANEL_ENTRYX                 2302
#define PANEL_DIALOG                 2400
#define PANEL_DIALOG_TAB             2401
#define PANEL_DIALOG_ENTRY1          2402
#define PANEL_DROP                   3000
#define PANEL_FILEDIALOG             4000
#define PANEL_CONTENTS               10000
#define PANEL_INDEX                  10001
#define PANEL_NONE                   1
