## Using Help - Help for Special Cases

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\helpothr.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -DIC_WIN -Fo$(ODIR)\helpothr.res
!endif


ALL : CREATEDIR $(ODIR)\helpothr.exe $(ODIR)\helpothr.hlp

!ifdef IC_PM
$(ODIR)\helpothr.exe : $(ODIR)\helpothr.obj $(ODIR)\childhlp.obj $(ODIR)\helpothr.res
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\helpothr.exe $(ODIR)\helpothr.obj \
       $(ODIR)\childhlp.obj
   $(RC) $(ODIR)\helpothr.res $(ODIR)\helpothr.exe
!else
$(ODIR)\helpothr.exe : $(ODIR)\helpothr.obj $(ODIR)\helpothr.res
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\helpothr.exe $(ODIR)\helpothr.obj \
       $(ODIR)\helpothr.res
!endif

$(ODIR)\helpothr.obj: helpothr.cpp helpothr.hpp helpothr.h hlppanel.h childhlp.hpp
!ifdef IPF_COMPATIBLE
   icc $(CFLAGS) /C+ /DIPF_COMPATIBLE /Fo$(ODIR)\helpothr.obj helpothr.cpp
!else
   icc $(CFLAGS) /C+ /Fo$(ODIR)\helpothr.obj helpothr.cpp
!endif

$(ODIR)\childhlp.obj: childhlp.cpp childhlp.hpp
   icc $(CFLAGS) /C+ /Fo$(ODIR)\childhlp.obj childhlp.cpp

$(ODIR)\helpothr.res: helpothr.rc helpothr.h hlppanel.h
   $(RC) -r helpothr.rc $(ORES)

!ifdef IC_PM
$(ODIR)\helpothr.hlp: helpothr.ipf hlppanel.h
   icc /Pc- /Pe+ /Tdp helpothr.ipf
   ipfc helpothr.i /x
   del  helpothr.i
!else
!ifdef IPF_COMPATIBLE
$(ODIR)\helpothr.hlp: helpothr.ipf hlppanel.h
   icc /Pc- /Pe+ /Tdp helpothr.ipf
   ipfc helpothr.i /x /q
   del  helpothr.i
!else
$(ODIR)\helpothr.hlp: helpothr.hpj helpothr.rtf hlppanel.h
   hcw /c /e helpothr.hpj
!endif
!endif
   copy helpothr.hlp $(ODIR)
   del  helpothr.hlp

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)

