## Frame Window Basics - Showing a Modal Frame Window

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
!else
ODIR=.\win
!endif


ALL : CREATEDIR $(ODIR)\modal.exe

$(ODIR)\modal.exe : $(ODIR)\modal.obj
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\modal.exe $(ODIR)\modal.obj

$(ODIR)\modal.obj: modal.cpp
   icc $(CFLAGS) /C+ /Fo$(ODIR)\modal.obj modal.cpp

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
