################################################################
# FILE NAME: makefile                                          #
#                                                              #
# DESCRIPTION:                                                 #
#   makefile for simple thread demo program                    #
#                                                              #
# COPYRIGHT:                                                   #
#   Licensed Materials - Property of Solution Frameworks       #
#   Copyright (C) 1996, Solution Frameworks                    #
#   All Rights Reserved                                        #
################################################################
CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
!else
ODIR=.\win
!endif


ALL :  CREATEDIR  $(ODIR)\simple.exe

$(ODIR)\simple.exe :  simple.cpp
   icc $(CFLAGS) /B"$(LFLAGS)" /Fo$(ODIR)\simple.obj /Fe$@ simple.cpp

CREATEDIR:
  @if not exist $(ODIR) md $(ODIR)

