## Lunch dialog - Sample Dialog Template

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\lunchdlg.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -DIC_WIN -Fo$(ODIR)\lunchdlg.res
!endif


ALL : CREATEDIR $(ODIR)\lunchdlg.exe

$(ODIR)\lunchdlg.exe : $(ODIR)\lunchdlg.obj $(ODIR)\lunchdlg.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\lunchdlg.exe $(ODIR)\lunchdlg.obj
   $(RC) $(ODIR)\lunchdlg.res $(ODIR)\lunchdlg.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\lunchdlg.exe \
       $(ODIR)\lunchdlg.obj $(ODIR)\lunchdlg.res
!endif

$(ODIR)\lunchdlg.obj: lunchdlg.cpp lunchdlg.h
   icc $(CFLAGS) /C+ /Fo$(ODIR)\lunchdlg.obj lunchdlg.cpp

$(ODIR)\lunchdlg.res: lunchdlg.rc lunchdlg.h
   $(RC) -r lunchdlg.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
