## Advanced Frame Window - Frame Style Test

CFLAGS = /Ft- /Gd+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
LIBS =
ODIR=.\os2
RC=rc.exe -DIC_PM
RCOUT=
!else
LIBS =
ODIR=.\win
RC=irc.exe
RCOUT=-Fo
!endif
ORES=$(ODIR)\fstyle.res

ALL :  CREATEDIR $(ODIR)\fstyle.exe

$(ODIR)\fstyle.exe : $(ODIR)\fstyle.obj $(ORES)
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" $(LIBS) /Fe$@ $(ODIR)\fstyle.obj
   $(RC) $(ORES) $@
!else
   icc $(CFLAGS) /B"$(LFLAGS)" $(LIBS) /Fe$@ $**
!endif

{.}.cpp{$(ODIR)}.obj:
   icc $(CFLAGS) /C+ /Fo$@ $(@B).cpp

$(ORES): fstyle.rc $(ODIR)\cpp.ico
   $(RC) -r $(@B).rc $(RCOUT)$@

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
