## Tool Bar - Tool Bar Fly-over Help Example   

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\flytbar.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\flytbar.res
!endif


ALL : CREATEDIR $(ODIR)\flytbar.exe

$(ODIR)\flytbar.exe :  $(ODIR)\flytbar.obj $(ODIR)\flytbar.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\flytbar.exe $(ODIR)\flytbar.obj
   $(RC) $(ODIR)\flytbar.res  $(ODIR)\flytbar.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\flytbar.exe  $(ODIR)\flytbar.obj $(ODIR)\flytbar.res
!endif

$(ODIR)\flytbar.obj: flytbar.cpp flytbar.h
   icc $(CFLAGS) /C+  /Fo$(ODIR)\flytbar.obj  flytbar.cpp

$(ODIR)\flytbar.res:  flytbar.rc flytbar.h 
   $(RC) -r flytbar.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
