/************************************************************
/ Using Help - Runtime Setting of Help Panels               
/                                                           
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ Copyright (c) 1997 John Wiley & Sons, Inc. 
/ All Rights Reserved.                                      
************************************************************/
// Help panel identifiers.
#define PANEL_PRIMARY                   1000
#define PANEL_LISTBOX                   1001
#define PANEL_FILE                      1003
#define PANEL_CHOICE1                   1004
#define PANEL_CHOICE2                   1005
#define PANEL_CLOSE                     1006 
#define PANEL_PRIMARY2                  2000
#define PANEL_ENTRY1_PRIMARY2           2001
#define PANEL_HELP_BUTTON_PRIMARY2      2002
#define PANEL_SEC_MODELESS              3000
#define PANEL_ENTRY1_SEC_MODELESS       3001
#define PANEL_HELP_BUTTON_SEC_MODELESS  3002
#define PANEL_SEC_MODAL                 4000
#define PANEL_ENTRY1_SEC_MODAL          4001
#define PANEL_HELP_BUTTON_SEC_MODAL     4002
#define PANEL_CONTENTS                 10000
#define PANEL_INDEX                    10001
