## Using Help - Runtime Setting of Help Panels

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\helpid.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -DIC_WIN -Fo$(ODIR)\helpid.res
!endif


ALL : CREATEDIR $(ODIR)\helpid.exe $(ODIR)\helpid.hlp

$(ODIR)\helpid.exe : $(ODIR)\helpid.obj $(ODIR)\helpid.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\helpid.exe $(ODIR)\helpid.obj
   $(RC) $(ODIR)\helpid.res $(ODIR)\helpid.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\helpid.exe $(ODIR)\helpid.obj \
       $(ODIR)\helpid.res
!endif

$(ODIR)\helpid.obj: helpid.cpp helpid.h hlppanel.h
!ifdef IPF_COMPATIBLE
   icc $(CFLAGS) /C+ /DIPF_COMPATIBLE /Fo$(ODIR)\helpid.obj helpid.cpp
!else
   icc $(CFLAGS) /C+ /Fo$(ODIR)\helpid.obj helpid.cpp
!endif

$(ODIR)\helpid.res: helpid.rc helpid.h hlppanel.h
   $(RC) -r helpid.rc $(ORES)

!ifdef IC_PM
$(ODIR)\helpid.hlp: helpid.ipf hlppanel.h
   icc /Pc- /Pe+ /Tdp helpid.ipf
   ipfc helpid.i /x
   del  helpid.i
!else
!ifdef IPF_COMPATIBLE
$(ODIR)\helpid.hlp: helpid.ipf hlppanel.h
   icc /Pc- /Pe+ /Tdp helpid.ipf
   ipfc helpid.i /x /q
   del  helpid.i
!else
$(ODIR)\helpid.hlp: helpid.hpj helpid.rtf hlppanel.h
   hcw /c /e helpid.hpj
!endif
!endif
   copy helpid.hlp $(ODIR)
   del  helpid.hlp

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)

