## Menus  - Defining a Menu Resource

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\dynsubmn.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\dynsubmn.res
!endif


ALL :  CREATEDIR  $(ODIR)\dynsubmn.exe

$(ODIR)\dynsubmn.exe :  $(ODIR)\dynsubmn.obj $(ODIR)\dynsubmn.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\dynsubmn.exe $(ODIR)\dynsubmn.obj
   $(RC) $(ODIR)\dynsubmn.res $(ODIR)\dynsubmn.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\dynsubmn.exe $(ODIR)\dynsubmn.obj $(ODIR)\dynsubmn.res
!endif

$(ODIR)\dynsubmn.obj : dynsubmn.cpp dynsubmn.h
   icc $(CFLAGS) /C+ /Fo$(ODIR)\dynsubmn.obj dynsubmn.cpp

$(ODIR)\dynsubmn.res : dynsubmn.rc dynsubmn.h
   $(RC) -r dynsubmn.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
