## Packaging and Performance Tuning - Modified Hello1

CFLAGS = /Ti+ /Gh+ /Ft- /Gd+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
PERFOBJ = cppopa3.obj
!else
ODIR=.\win
PERFOBJ = cppwpa3.obj
!endif

ALL : CREATEDIR $(ODIR)\hello1.exe

$(ODIR)\hello1.exe : $(ODIR)\hello1.obj
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$@ $** $(PERFOBJ)

{.}.cpp{$(ODIR)}.obj:
   icc $(CFLAGS) /C+ -Fo$@ $(*B).cpp

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
