## Notebook Control - Adding Dialog Pages

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\addpages.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\addpages.res
!endif


ALL : CREATEDIR $(ODIR)\addpages.exe

$(ODIR)\addpages.exe :  $(ODIR)\addpages.obj $(ODIR)\addpages.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\addpages.exe $(ODIR)\addpages.obj
   $(RC) $(ODIR)\addpages.res  $(ODIR)\addpages.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\addpages.exe  $(ODIR)\addpages.obj $(ODIR)\addpages.res
!endif

$(ODIR)\addpages.obj: addpages.cpp addpages.h
   icc $(CFLAGS) /C+  /Fo$(ODIR)\addpages.obj  addpages.cpp

$(ODIR)\addpages.res:  addpages.rc addpages.h
   $(RC) -r addpages.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
