## GUI Profile Viewer Example

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\profile.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\profile.res
!endif

OBJS = $(ODIR)\profile.obj \
       $(ODIR)\appview.obj \
       $(ODIR)\profview.obj \
       $(ODIR)\profobj.obj \
       $(ODIR)\enhprof.obj \
       $(ODIR)\keyview.obj \
       $(ODIR)\vprofarg.obj

ALL : CREATEDIR   $(ODIR)\profile.exe

$(ODIR)\profile.exe :  $(OBJS) $(ODIR)\profile.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\profile.exe $(OBJS)
   $(RC) $(ODIR)\profile.res  $(ODIR)\profile.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\profile.exe  $(OBJS) $(ODIR)\profile.res
!endif

$(ODIR)\profile.obj: profview.hpp vprofarg.hpp enhprof.hpp
   icc $(CFLAGS) /C+  /Fo$(ODIR)\profile.obj  profile.cpp

$(ODIR)\appview.obj: appview.hpp keyview.hpp profview.hpp
   icc $(CFLAGS) /C+  /Fo$(ODIR)\appview.obj  appview.cpp

$(ODIR)\profview.obj: profview.hpp profview.h appview.hpp keyview.hpp enhprof.hpp
   icc $(CFLAGS) /C+  /Fo$(ODIR)\profview.obj  profview.cpp

$(ODIR)\profobj.obj: profobj.hpp
   icc $(CFLAGS) /C+  /Fo$(ODIR)\profobj.obj  profobj.cpp

$(ODIR)\enhprof.obj: enhprof.hpp
   icc $(CFLAGS) /C+  /Fo$(ODIR)\enhprof.obj  enhprof.cpp

$(ODIR)\vprofarg.obj: vprofarg.hpp
   icc $(CFLAGS) /C+  /Fo$(ODIR)\vprofarg.obj  vprofarg.cpp

$(ODIR)\keyview.obj: keyview.hpp  profview.hpp
   icc $(CFLAGS) /C+  /Fo$(ODIR)\keyview.obj  keyview.cpp


$(ODIR)\profile.res:  profile.rc profview.h
   $(RC) -r profile.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)

