## Reusable Commands - Processing Mouse Pointer Movement

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
!else
ODIR=.\win
!endif


ALL : CREATEDIR $(ODIR)\mousemov.exe

$(ODIR)\mousemov.exe : $(ODIR)\mousemov.obj
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\mousemov.exe $(ODIR)\mousemov.obj

$(ODIR)\mousemov.obj: mousemov.cpp
   icc $(CFLAGS) /C+ /Fo$(ODIR)\mousemov.obj mousemov.cpp

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
