## Menus - Static Text Pop-up Example

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\txtpopup.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\txtpopup.res
!endif


ALL :  CREATEDIR  $(ODIR)\txtpopup.exe

$(ODIR)\txtpopup.exe :  $(ODIR)\txtpopup.obj $(ODIR)\txtpopup.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\txtpopup.exe $(ODIR)\txtpopup.obj
   $(RC) $(ODIR)\txtpopup.res $(ODIR)\txtpopup.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\txtpopup.exe $(ODIR)\txtpopup.obj $(ODIR)\txtpopup.res
!endif

$(ODIR)\txtpopup.obj : txtpopup.cpp txtpopup.h
   icc $(CFLAGS) /C+ /Fo$(ODIR)\txtpopup.obj txtpopup.cpp

$(ODIR)\txtpopup.res : txtpopup.rc txtpopup.h
   $(RC) -r txtpopup.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
