## Advanced Frame - Frame Save Handler

CFLAGS = /Ft- /Gd+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
LIBS =
ODIR=.\os2
!else
LIBS =
ODIR=.\win
!endif

ALL :  CREATEDIR $(ODIR)\framesav.exe

$(ODIR)\framesav.exe : $(ODIR)\framesav.obj $(ODIR)\savhndlr.obj
   icc $(CFLAGS) /B"$(LFLAGS)" $(LIBS) /Fe$@ $**

framesav.cpp  : savhndlr.hpp
savhndlr.cpp  : savhndlr.hpp

{.}.cpp{$(ODIR)}.obj:
   icc $(CFLAGS) /C+ /Fo$@ $(@B).cpp

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)

