## Problem Determination - Using a Zero Pointer

CFLAGS = /Ti+ /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
!else
ODIR=.\win
!endif

ALL : CREATEDIR $(ODIR)\zeroptr.exe

$(ODIR)\zeroptr.exe : $(ODIR)\zeroptr.obj
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$@ $**

{.}.cpp{$(ODIR)}.obj:
   icc $(CFLAGS) /C+ -Fo$@ $(*B).cpp

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
