## Canvas - ISplitCanvas with "Problem" Child Windows

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
!else
ODIR=.\win
!endif


ALL : CREATEDIR $(ODIR)\splitprb.exe

$(ODIR)\splitprb.exe : $(ODIR)\splitprb.obj
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\splitprb.exe $(ODIR)\splitprb.obj

$(ODIR)\splitprb.obj: splitprb.cpp
   icc $(CFLAGS) /C+ /Fo$(ODIR)\splitprb.obj splitprb.cpp

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
