## Frame Window Basics - Minimize/Maximize Handler

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\minmax.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\minmax.res
!endif


ALL :  CREATEDIR  $(ODIR)\minmax.exe

$(ODIR)\minmax.exe : $(ODIR)\minmax.obj $(ODIR)\minmaxh.obj $(ODIR)\chdhider.obj \
                     $(ODIR)\minmax.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\minmax.exe $(ODIR)\minmax.obj \
                 $(ODIR)\minmaxh.obj $(ODIR)\chdhider.obj
   $(RC) $(ODIR)\minmax.res $(ODIR)\minmax.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\minmax.exe $(ODIR)\minmax.obj \
                 $(ODIR)\minmaxh.obj $(ODIR)\chdhider.obj $(ODIR)\minmax.res user32.lib
!endif

$(ODIR)\minmax.obj: minmax.cpp chdhider.hpp
   icc $(CFLAGS) /C+ /Fo$(ODIR)\minmax.obj minmax.cpp

$(ODIR)\minmaxh.obj: minmaxh.cpp minmaxh.hpp
   icc $(CFLAGS) /C+ /Fo$(ODIR)\minmaxh.obj minmaxh.cpp

$(ODIR)\chdhider.obj: chdhider.cpp chdhider.hpp minmaxh.hpp
   icc $(CFLAGS) /C+ /Fo$(ODIR)\chdhider.obj chdhider.cpp

$(ODIR)\minmax.res: minmax.rc $(ODIR)\minmax.ico
   $(RC) -r minmax.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
