## Reusable Handlers - Keyboard Handler

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\keybd.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -DIC_WIN -Fo$(ODIR)\keybd.res
!endif


ALL :  CREATEDIR  $(ODIR)\keybd.exe

$(ODIR)\keybd.exe : $(ODIR)\keybd.obj $(ODIR)\keybd.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\keybd.exe $(ODIR)\keybd.obj
   $(RC) $(ODIR)\keybd.res $(ODIR)\keybd.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\keybd.exe $(ODIR)\keybd.obj $(ODIR)\keybd.res
!endif

$(ODIR)\keybd.obj: keybd.cpp uckeybd.hpp keybd.h
   icc $(CFLAGS) /C+ /Fo$(ODIR)\keybd.obj keybd.cpp

$(ODIR)\keybd.res: keybd.rc keybd.h
   $(RC) -r keybd.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
