#ifndef  _FILTDLG_H_
#define  _FILTDLG_H_
/************************************************************
/ Problem Determination  - Trace Queue Browser
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ Copyright (c) 1997 John Wiley & Sons, Inc. 
/ All Rights Reserved.
************************************************************/

#define  FLTD_DIALOG       1
#define  FLTD_CANVAS       0x8008
#define  FLTD_LABEL        100
#define  FLTD_ENTRY        101
#define  FLTD_LIST         102
#define  FLTD_BUTTONS1     103
#define  FLTD_ADD          104
#define  FLTD_REMOVE       105
#define  FLTD_BUTTONS2     106
#define  FLTD_OK           107
#define  FLTD_CANCEL       108
#define  FLTD_EXCLUDE      109
#define  FLTD_LABEL0       110
#define  FLTD_LABEL1       111

#endif
