## Views - Using the Font Dialog

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\fontdlg.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\fontdlg.res
!endif


ALL :  CREATEDIR  $(ODIR)\fontdlg.exe

$(ODIR)\fontdlg.exe :  $(ODIR)\fontdlg.obj $(ODIR)\fontdlg.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\fontdlg.exe $(ODIR)\fontdlg.obj
   $(RC) $(ODIR)\fontdlg.res $(ODIR)\fontdlg.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\fontdlg.exe $(ODIR)\fontdlg.obj $(ODIR)\fontdlg.res
!endif

$(ODIR)\fontdlg.obj : fontdlg.cpp fontdlg.h
   icc $(CFLAGS) /C+ /Fo$(ODIR)\fontdlg.obj fontdlg.cpp

$(ODIR)\fontdlg.res : fontdlg.rc fontdlg.h
   $(RC) -r fontdlg.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
