################################################################
# FILE NAME: makefile                                          #
#                                                              #
# DESCRIPTION:                                                 #
#   makefile for userevt.obj (component used by other          #
#   thread sample programs)                                    #
#                                                              #
# COPYRIGHT:                                                   #
#   Licensed Materials - Property of Solution Frameworks       #
#   Copyright (C) 1996, Solution Frameworks                    #
#   All Rights Reserved                                        #
################################################################
CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:VIO

!ifdef IC_PM
ODIR=.\os2
!else
ODIR=.\win
!endif


ALL :  CREATEDIR  $(ODIR)\userevt.obj

$(ODIR)\userevt.obj: userevt.cpp userevt.hpp
   icc $(CFLAGS) /C+ /Fo$(ODIR)\userevt.obj  userevt.cpp

CREATEDIR:
  @if not exist $(ODIR) md $(ODIR)

