## Menus  - Using an Accelerator Table Resource

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\accel.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\accel.res
!endif


ALL :  CREATEDIR  $(ODIR)\accel.exe

$(ODIR)\accel.exe :  $(ODIR)\accel.obj $(ODIR)\accel.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\accel.exe $(ODIR)\accel.obj
   $(RC) $(ODIR)\accel.res $(ODIR)\accel.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\accel.exe $(ODIR)\accel.obj $(ODIR)\accel.res
!endif

$(ODIR)\accel.obj : accel.cpp accel.h
   icc $(CFLAGS) /C+ /Fo$(ODIR)\accel.obj accel.cpp

$(ODIR)\accel.res : accel.rc accel.h
   $(RC) -r accel.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
