## Canvas - ISetCanvas Deck Operations

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\setdecks.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -DIC_WIN -Fo$(ODIR)\setdecks.res
!endif


ALL : CREATEDIR $(ODIR)\setdecks.exe

$(ODIR)\setdecks.exe : $(ODIR)\setdecks.obj $(ODIR)\deckcv.obj $(ODIR)\setdecks.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\setdecks.exe $(ODIR)\setdecks.obj \
       $(ODIR)\deckcv.obj
   $(RC) $(ODIR)\setdecks.res $(ODIR)\setdecks.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\setdecks.exe $(ODIR)\setdecks.obj \
       $(ODIR)\deckcv.obj $(ODIR)\setdecks.res
!endif

$(ODIR)\setdecks.obj: setdecks.cpp deckcv.hpp setdecks.h
   icc $(CFLAGS) /C+ /Fo$(ODIR)\setdecks.obj setdecks.cpp

$(ODIR)\deckcv.obj: deckcv.cpp deckcv.hpp setdecks.h
   icc $(CFLAGS) /C+ /Fo$(ODIR)\deckcv.obj deckcv.cpp

$(ODIR)\setdecks.res: setdecks.rc setdecks.h
   $(RC) -r setdecks.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
