## Menus - Title Bar Bitmaps

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\titlebmp.res
RC=rc.exe -DIC_PM


ALL :  CREATEDIR  $(ODIR)\titlebmp.exe

$(ODIR)\titlebmp.exe :  $(ODIR)\titlebmp.obj $(ODIR)\titlebmp.res
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\titlebmp.exe $(ODIR)\titlebmp.obj
   $(RC) $(ODIR)\titlebmp.res $(ODIR)\titlebmp.exe

$(ODIR)\titlebmp.obj : titlebmp.cpp titlebmp.h
   icc $(CFLAGS) /C+ /Fo$(ODIR)\titlebmp.obj titlebmp.cpp

$(ODIR)\titlebmp.res : titlebmp.rc titlebmp.h
   $(RC) -r titlebmp.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
!else
ALL :  DISPLAYMSG

DISPLAYMSG:
  @echo This sample is not supported on the Windows operating systems.
!endif

