## Problem Determination - Simple Trace Example

CFLAGS = -DIC_DEVELOP /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:VIO

!ifdef IC_PM
ODIR=.\os2
!else
ODIR=.\win
!endif

ALL : CREATEDIR $(ODIR)\trace.exe

$(ODIR)\trace.exe : $(ODIR)\trace.obj
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$@ $**

{.}.cpp{$(ODIR)}.obj:
   icc $(CFLAGS) /C+ -Fo$@ $(*B).cpp

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
