## Container Control - Spreadsheet Behavior

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\spreadsh.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\spreadsh.res
!endif


ALL : CREATEDIR   $(ODIR)\spreadsh.exe

$(ODIR)\spreadsh.exe :  $(ODIR)\spreadsh.obj $(ODIR)\sprdhdr.obj $(ODIR)\table.obj $(ODIR)\spreadsh.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\spreadsh.exe $(ODIR)\spreadsh.obj  $(ODIR)\sprdhdr.obj $(ODIR)\table.obj
   $(RC) $(ODIR)\spreadsh.res  $(ODIR)\spreadsh.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\spreadsh.exe  $(ODIR)\spreadsh.obj $(ODIR)\sprdhdr.obj $(ODIR)\table.obj $(ODIR)\spreadsh.res
!endif

$(ODIR)\spreadsh.obj: spreadsh.cpp table.hpp sprdhdr.hpp
   icc $(CFLAGS) /C+  /Fo$(ODIR)\spreadsh.obj  spreadsh.cpp

$(ODIR)\sprdhdr.obj: sprdhdr.hpp
   icc $(CFLAGS) /C+  /Fo$(ODIR)\sprdhdr.obj  sprdhdr.cpp

$(ODIR)\table.obj: table.hpp
   icc $(CFLAGS) /C+  /Fo$(ODIR)\table.obj  table.cpp

$(ODIR)\spreadsh.res:  spreadsh.rc spreadsh.h
   $(RC) -r spreadsh.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
