## Container Control - Pop Up Menu Example

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\popup.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\popup.res
!endif


ALL : CREATEDIR   $(ODIR)\popup.exe

$(ODIR)\popup.exe :  $(ODIR)\popup.obj $(ODIR)\popup.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\popup.exe $(ODIR)\popup.obj
   $(RC) $(ODIR)\popup.res  $(ODIR)\popup.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\popup.exe  $(ODIR)\popup.obj $(ODIR)\popup.res
!endif

$(ODIR)\popup.obj: popup.cpp popup.h
   icc $(CFLAGS) /C+  /Fo$(ODIR)\popup.obj  popup.cpp

$(ODIR)\popup.res:  popup.rc popup.h
   $(RC) -r popup.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
