/************************************************************
/ Container Control - Pop Up Menu Example 
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ Copyright (c) 1997 John Wiley & Sons, Inc. 
/ All Rights Reserved.
************************************************************/
#define ICON_FOLDER 0x1000

#define POPUP_MENU        0x1001
#define   EDIT_SUBMENU    0x1002
#define     COPY_OBJECT   0x1003
#define     CUT_OBJECT    0x1004
#define     PASTE_OBJECT  0x1005
