## Advanced Frame - MDI Frame Example

CFLAGS = /Ft- /Gd+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
LIBS =
ODIR=.\os2
RC=rc.exe -DIC_PM
RCOUT=
!else
LIBS = user32.lib
ODIR=.\win
RC=irc.exe
RCOUT=-Fo
!endif
ORES=$(ODIR)\mdi.res

OBJS = $(ODIR)\mdi.obj  \
       $(ODIR)\editwin.obj  \
       $(ODIR)\mdiwin.obj

ALL: CREATEDIR $(ODIR)\mdi.exe

$(ODIR)\mdi.exe : $(OBJS) $(ORES)
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" $(LIBS) /Fe$@ $(OBJS)
   $(RC) $(ORES) $@
!else
   icc $(CFLAGS) /B"$(LFLAGS)" $(LIBS) /Fe$@ $**
!endif

mdi.cpp      : editwin.hpp mdiwin.hpp
editwin.cpp  : editwin.hpp mdiwin.hpp mdi.h
mdiwin.cpp   : mdiwin.hpp

{.}.cpp{$(ODIR)}.obj:
   icc $(CFLAGS) /C+ /Fo$@ $(@B).cpp

$(ORES): mdi.rc mdi.h $(ODIR)\app.ico $(ODIR)\view.ico
   $(RC) -r $(@B).rc $(RCOUT)$@

CREATEDIR:
  @if not exist $(ODIR) mkdir $(ODIR)
