/************************************************************
/ Advanced Frame - MDI Frame Example
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ Copyright (c) 1997 John Wiley & Sons, Inc. 
/ All Rights Reserved.
************************************************************/

#define WND_MAIN    100

#define MI_FILE        100
#define MI_OPEN        101
#define MI_CLOSE       102
#define MI_EXIT        110
#define MI_WINDOWS     400
#define MI_CASCADE     401
#define MI_TILEH       402
#define MI_TILEV       403
#define MI_ARRANGE     404
#define MI_FIRSTCHILD  410

#define APP_ICON_ID 101
