//************************************************************
// Advanced Frame - MDI Frame Example
//
// Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
// Copyright (c) 1997 John Wiley & Sons, Inc. 
// All Rights Reserved.
//************************************************************
#include "editwin.hpp"

int main (  )
{
  MainWindow
    mainWindow;
  IApplication::current().run();
  return 0;
}
