## Tool Bars - Tool Bar With Decks Example

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
!else
ODIR=.\win
!endif


ALL : CREATEDIR   $(ODIR)\tbardeck.exe

$(ODIR)\tbardeck.exe :  $(ODIR)\tbardeck.obj
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\tbardeck.exe $(ODIR)\tbardeck.obj

$(ODIR)\tbardeck.obj: tbardeck.cpp
   icc $(CFLAGS) /C+  /Fo$(ODIR)\tbardeck.obj  tbardeck.cpp

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
