## Container Control - Tree Name View

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\nameview.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\nameview.res
!endif


ALL : CREATEDIR   $(ODIR)\nameview.exe

$(ODIR)\nameview.exe :  $(ODIR)\nameview.obj $(ODIR)\nameview.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\nameview.exe $(ODIR)\nameview.obj
   $(RC) $(ODIR)\nameview.res  $(ODIR)\nameview.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\nameview.exe  $(ODIR)\nameview.obj $(ODIR)\nameview.res
!endif

$(ODIR)\nameview.obj: nameview.cpp nameview.h
   icc $(CFLAGS) /C+  /Fo$(ODIR)\nameview.obj  nameview.cpp

$(ODIR)\nameview.res:  nameview.rc nameview.h
   $(RC) -r nameview.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
