/************************************************************
/ Views - Using the File Dialog
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ Copyright (c) 1997 John Wiley & Sons, Inc. 
/ All Rights Reserved.
************************************************************/
#define MAIN_WINDOW        1000

#define MI_FILE            1050
#define MI_OPENDLG         1051
#define MI_SAVEASDLG       1052
#define MI_EXIT            1053

