## Views - Using the File Dialog

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\filedlg.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\filedlg.res
!endif


ALL :  CREATEDIR  $(ODIR)\filedlg.exe

$(ODIR)\filedlg.exe :  $(ODIR)\filedlg.obj $(ODIR)\filedlg.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\filedlg.exe $(ODIR)\filedlg.obj
   $(RC) $(ODIR)\filedlg.res $(ODIR)\filedlg.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\filedlg.exe $(ODIR)\filedlg.obj $(ODIR)\filedlg.res
!endif

$(ODIR)\filedlg.obj : filedlg.cpp filedlg.h
   icc $(CFLAGS) /C+ /Fo$(ODIR)\filedlg.obj filedlg.cpp

$(ODIR)\filedlg.res : filedlg.rc filedlg.h
   $(RC) -r filedlg.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
