//************************************************************
// Edit Controls - Using an Edit Handler example
//
// Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
// Copyright (c) 1997 John Wiley & Sons, Inc. 
// All Rights Reserved.
//************************************************************

#define MAIN_MENU          1001
#define ID_STATUS          1002
#define ID_LOGON           1003
#define ID_LOGONMCC        1010
#define ID_LOGONIDPMT      1011
#define ID_LOGONPWPMT      1012
#define ID_LOGONID         1013
#define ID_LOGONPW         1014
#define ID_PASSWORD        1015
#define ID_OKBUTTON        1

#define MI_OPTIONS         1050
#define MI_LOGON           1051
#define SI_LOGONPASSED     1060
#define SI_LOGONFAILED     1061

