## Edit Controls - Using an Edit Handler example

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\logon.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\logon.res
!endif


ALL :  CREATEDIR  $(ODIR)\logon.exe

$(ODIR)\logon.exe :  $(ODIR)\logon.obj $(ODIR)\logon.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\logon.exe $(ODIR)\logon.obj
   $(RC) $(ODIR)\logon.res $(ODIR)\logon.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\logon.exe $(ODIR)\logon.obj $(ODIR)\logon.res
!endif

$(ODIR)\logon.obj : logon.cpp logon.h
   icc $(CFLAGS) /C+ /Fo$(ODIR)\logon.obj logon.cpp

$(ODIR)\logon.res : logon.rc logon.h
   $(RC) -r logon.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
