## Menus  - Creating Pop-up Menus Dynamically

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\dynpopup.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\dynpopup.res
!endif


ALL :  CREATEDIR  $(ODIR)\dynpopup.exe

$(ODIR)\dynpopup.exe :  $(ODIR)\dynpopup.obj $(ODIR)\dynpopup.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\dynpopup.exe $(ODIR)\dynpopup.obj
   $(RC) $(ODIR)\dynpopup.res $(ODIR)\dynpopup.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\dynpopup.exe $(ODIR)\dynpopup.obj $(ODIR)\dynpopup.res
!endif

$(ODIR)\dynpopup.obj : dynpopup.cpp dynpopup.h
   icc $(CFLAGS) /C+ /Fo$(ODIR)\dynpopup.obj dynpopup.cpp

$(ODIR)\dynpopup.res : dynpopup.rc dynpopup.h
   $(RC) -r dynpopup.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
