## Container Control - Text View Example

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
!else
ODIR=.\win
!endif


ALL : CREATEDIR   $(ODIR)\textview.exe

$(ODIR)\textview.exe :  $(ODIR)\textview.obj
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\textview.exe $(ODIR)\textview.obj

$(ODIR)\textview.obj: textview.cpp
   icc $(CFLAGS) /C+  /Fo$(ODIR)\textview.obj  textview.cpp

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
