## Menus - Custom Drawing Example

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\drawmenu.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\drawmenu.res
!endif


ALL :  CREATEDIR  $(ODIR)\drawmenu.exe

$(ODIR)\drawmenu.exe :  $(ODIR)\drawmenu.obj $(ODIR)\drawmenu.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\drawmenu.exe $(ODIR)\drawmenu.obj
   $(RC) $(ODIR)\drawmenu.res $(ODIR)\drawmenu.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\drawmenu.exe $(ODIR)\drawmenu.obj $(ODIR)\drawmenu.res
!endif

$(ODIR)\drawmenu.obj : drawmenu.cpp drawmenu.h
   icc $(CFLAGS) /C+ /Fo$(ODIR)\drawmenu.obj drawmenu.cpp

$(ODIR)\drawmenu.res : drawmenu.rc drawmenu.h
   $(RC) -r drawmenu.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
