/************************************************************
/ Tour of the UICL - Shopping List Example Program
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ Copyright (c) 1997 John Wiley & Sons, Inc. 
/ All Rights Reserved.
************************************************************/
#include <icconst.h>
#define ID_THEBOOKICON         100
#define ID_THEBOOKBITMAP       200

// Primary window identifiers.
#define ID_SHOPPINGLIST        1000
#define ID_LISTCLIENT          IC_FRAME_CLIENT_ID
#define ID_BUYLIST             1001
#define ID_DONTBUYLIST         1002
#define ID_TOOLBAR             1003
#define ID_FLYTEXT             1004

// PurchaseItem view window identifiers.
#define ID_PURCHASEITEMVIEW    2000
#define ID_PURCHASEITEMBOOK    IC_FRAME_CLIENT_ID
#define ID_PURCHASEITEMPAGE1   2001
#define ID_NAMEPROMPT          2002
#define ID_NAME                2003
#define ID_QUANTITYPROMPT      2004
#define ID_QUANTITY            2005
#define ID_MANUFACTURERPROMPT  2006
#define ID_MANUFACTURER        2007
#define ID_PRICEPROMPT         2008
#define ID_PRICE               2009
#define ID_NOTESPROMPT         2010
#define ID_NOTES               2011
#define ID_BITMAPBUTTON        2012
#define ID_PURCHASEITEMPAGE2   2013
#define ID_POWERBITMAP         2500


