## Canvas - IViewPort that Scrolls a Bitmap

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\vportbmp.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\vportbmp.res
!endif


ALL : CREATEDIR $(ODIR)\vportbmp.exe

$(ODIR)\vportbmp.exe : $(ODIR)\vportbmp.obj $(ODIR)\vportcmd.obj $(ODIR)\vportbmp.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\vportbmp.exe $(ODIR)\vportbmp.obj \
       $(ODIR)\vportcmd.obj
   $(RC) $(ODIR)\vportbmp.res $(ODIR)\vportbmp.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\vportbmp.exe $(ODIR)\vportbmp.obj \
       $(ODIR)\vportcmd.obj $(ODIR)\vportbmp.res
!endif

$(ODIR)\vportbmp.obj: vportbmp.cpp vportcmd.hpp vportbmp.h
   icc $(CFLAGS) /C+ /Fo$(ODIR)\vportbmp.obj vportbmp.cpp

$(ODIR)\vportcmd.obj: vportcmd.cpp vportcmd.hpp vportbmp.h
   icc $(CFLAGS) /C+ /Fo$(ODIR)\vportcmd.obj vportcmd.cpp

$(ODIR)\vportbmp.res: vportbmp.rc vportbmp.h
   $(RC) -r vportbmp.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
