/**********************************************************
/ Canvas - IViewPort that Scrolls a Bitmap
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ Copyright (c) 1997 John Wiley & Sons, Inc. 
/ All Rights Reserved.
**********************************************************/
#define ID_BITMAP                 100
#define ID_DEFAULT_BMP            101
#define ID_FOUNTAIN_BMP           101
#define ID_KIDS_BMP               102
#define ID_OLDBOOK_BMP            103

#define ID_DOUBLE_SIZE            201
#define ID_HALVE_SIZE             202

#define ID_VIEWPORT               300
#define ID_SCROLL_TO_TOP          301
#define ID_SCROLL_TO_VERT_MIDDLE  302
#define ID_SCROLL_TO_BOTTOM       303
#define ID_SCROLL_TO_LEFT         304
#define ID_SCROLL_TO_MIDDLE       305
#define ID_SCROLL_TO_RIGHT        306
