## Menus  - Defining a Menu Resource

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\menures.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\menures.res
!endif


ALL :  CREATEDIR  $(ODIR)\menures.exe

$(ODIR)\menures.exe :  $(ODIR)\menures.obj $(ODIR)\menures.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\menures.exe $(ODIR)\menures.obj
   $(RC) $(ODIR)\menures.res $(ODIR)\menures.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\menures.exe $(ODIR)\menures.obj $(ODIR)\menures.res
!endif

$(ODIR)\menures.obj : menures.cpp menures.h
   icc $(CFLAGS) /C+ /Fo$(ODIR)\menures.obj menures.cpp

$(ODIR)\menures.res : menures.rc menures.h
   $(RC) -r menures.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
