## Frame Window Basics - Loading a Dialog Template

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\dialog.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\dialog.res
!endif


ALL :  CREATEDIR  $(ODIR)\dialog.exe

$(ODIR)\dialog.exe : $(ODIR)\dialog.obj $(ODIR)\dialog.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\dialog.exe $(ODIR)\dialog.obj
   $(RC) $(ODIR)\dialog.res $(ODIR)\dialog.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\dialog.exe $(ODIR)\dialog.obj $(ODIR)\dialog.res
!endif

$(ODIR)\dialog.obj: dialog.cpp dialog.h
   icc $(CFLAGS) /C+ /Fo$(ODIR)\dialog.obj dialog.cpp

$(ODIR)\dialog.res: dialog.rc dialog.h
   $(RC) -r dialog.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
