## Problem Determination  - Trace Queue Browser

CFLAGS = /Ft- /Gd+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
!else
ODIR=.\win
!endif

ALL : CREATEDIR $(ODIR)\prtque.exe

$(ODIR)\prtque.exe : $(ODIR)\prtque.obj $(ODIR)\querdr.obj $(ODIR)\trbrowse.obj
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$@ $**

prtque.cpp   : trbrowse.hpp

trbrowse.cpp : trbrowse.hpp trbrowse.h

querdr.cpp   : querdr.hpp trbrowse.h

{.}.cpp{$(ODIR)}.obj:
   icc $(CFLAGS) /C+ -Fo$@ $(@B).cpp

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
