/************************************************************
/ Problem Determination  - Trace Queue Browser
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ Copyright (c) 1997 John Wiley & Sons, Inc. 
/ All Rights Reserved.
************************************************************/
// Note: 0x1000 is in WM_USER range
#define ADD_OBJECT     0x1000 + 100
#define START_QUEUE    0x1000 + 101
