## Container Control - Container Help

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\help.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\help.res
!endif


ALL : CREATEDIR   $(ODIR)\help.hlp $(ODIR)\help.exe

$(ODIR)\help.exe : $(ODIR)\help.obj $(ODIR)\help.res $(ODIR)\devmodel.obj $(ODIR)\devview.obj
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\help.exe $(ODIR)\help.obj $(ODIR)\devmodel.obj $(ODIR)\devview.obj
   $(RC) $(ODIR)\help.res  $(ODIR)\help.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\help.exe  $(ODIR)\help.obj $(ODIR)\devmodel.obj $(ODIR)\devview.obj $(ODIR)\help.res
!endif

$(ODIR)\help.obj: help.cpp devview.hpp
   icc $(CFLAGS) /C+  /Fo$(ODIR)\help.obj  help.cpp

$(ODIR)\devview.obj: devview.cpp devview.hpp devview.h devmodel.hpp
   icc $(CFLAGS) /C+  /Fo$(ODIR)\devview.obj  devview.cpp

$(ODIR)\devmodel.obj: devmodel.cpp devmodel.hpp
   icc $(CFLAGS) /C+  /Fo$(ODIR)\devmodel.obj  devmodel.cpp

$(ODIR)\help.res:  help.rc devview.h
   $(RC) -r help.rc $(ORES)

$(ODIR)\help.hlp: help.ipf devview.h
   icc /Pc- /Pe+ /Tdp  help.ipf
!ifdef IC_PM
   ipfc help.i 
!else
   ipfc help.i  /q
!endif
   copy help.hlp $(ODIR)
   del  help.hlp

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
