/************************************************************
/ Tool Bar - Basic Fly-over Help Example  
/
/ Copyright (C) 1994, Law, Leong, Love, Olson, Tsuji.
/ Copyright (c) 1997 John Wiley & Sons, Inc. 
/ All Rights Reserved.
************************************************************/
#define FLYTEXT_OFFSET     500
#define LONGTEXT_OFFSET   1000

#define ID_BUTTON1           1
#define ID_BUTTON2           2
#define ID_FLYTEXT           3
