## Tool Bar - Basic Fly-over Help Example   

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\flybasic.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\flybasic.res
!endif


ALL : CREATEDIR $(ODIR)\flybasic.exe

$(ODIR)\flybasic.exe :  $(ODIR)\flybasic.obj $(ODIR)\flybasic.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\flybasic.exe $(ODIR)\flybasic.obj
   $(RC) $(ODIR)\flybasic.res  $(ODIR)\flybasic.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\flybasic.exe  $(ODIR)\flybasic.obj $(ODIR)\flybasic.res
!endif

$(ODIR)\flybasic.obj: flybasic.cpp flybasic.h
   icc $(CFLAGS) /C+  /Fo$(ODIR)\flybasic.obj  flybasic.cpp

$(ODIR)\flybasic.res:  flybasic.rc flybasic.h 
   $(RC) -r flybasic.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
