## Menus  - Using an IMenuBar

CFLAGS = /Ft- /Gd+ /Ge+ /Gm+ /Wall+gnr-ppc-ppt-uni-vft-
LFLAGS = /PM:PM

!ifdef IC_PM
ODIR=.\os2
ORES=$(ODIR)\menubar.res
RC=rc.exe -DIC_PM
!else
ODIR=.\win
ORES=
RC=irc.exe -Fo$(ODIR)\menubar.res
!endif


ALL :  CREATEDIR  $(ODIR)\menubar.exe

$(ODIR)\menubar.exe :  $(ODIR)\menubar.obj $(ODIR)\menubar.res
!ifdef IC_PM
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\menubar.exe $(ODIR)\menubar.obj
   $(RC) $(ODIR)\menubar.res $(ODIR)\menubar.exe
!else
   icc $(CFLAGS) /B"$(LFLAGS)" /Fe$(ODIR)\menubar.exe $(ODIR)\menubar.obj $(ODIR)\menubar.res
!endif

$(ODIR)\menubar.obj : menubar.cpp menubar.h
   icc $(CFLAGS) /C+ /Fo$(ODIR)\menubar.obj menubar.cpp

$(ODIR)\menubar.res : menubar.rc menubar.h
   $(RC) -r menubar.rc $(ORES)

CREATEDIR:
  @if not exist $(ODIR)* md $(ODIR)
